// Pure Gemini CLI Policy Engine TOML render, mirroring permissions-render.mjs's
// claudePermissions/renderCodexConfig for the third provider. No file I/O, no path resolution —
// the provider adapter (scripts/harnesses/gemini/index.mjs) supplies the target directory/paths.
//
// Gemini's Policy Engine (~/.gemini/policies/*.toml, User tier) is the only one of the three
// providers with a real native 3-state decision (allow/deny/ask_user) at the config layer — no
// approximation or session-wide fallback needed, unlike Codex's binary prefix_rule + approval_policy
// fallback. Each manifest behavior/command resolves to exactly one [[rule]].
//
// Tool-name mapping verified against the installed @google/gemini-cli@0.53.1 bundle's own tool-name
// constants (chunk-2NH5AG3B.js: WRITE_FILE_TOOL_NAME="write_file", EDIT_TOOL_NAME="replace",
// READ_FILE_TOOL_NAME="read_file"), not guessed from docs — this is the complete, exhaustive set of
// write/read tool names Gemini ships, sourced from the binary itself.
const CLAUDE_TOOL_TO_GEMINI = {
  Write: "write_file",
  Edit: "replace",
  Read: "read_file",
};

function geminiToolNames(claudeToolNames) {
  return claudeToolNames.map((name) => CLAUDE_TOOL_TO_GEMINI[name]).filter(Boolean);
}

function quoteToml(value) {
  return JSON.stringify(String(value));
}

function tomlToolNameField(names) {
  if (names.length === 1) return quoteToml(names[0]);
  return `[${names.map(quoteToml).join(", ")}]`;
}

// User tier priority: 0-999 range per rule, tier base (4) applied by the engine itself at load
// time (final_priority = 4 + priority/1000) — the TOML file only ever writes the 0-999 value.
const RULE_PRIORITY = 500;

// Manifest buckets are "allow"/"deny"/"ask" (shared vocabulary with Claude/Codex); the Policy
// Engine's own decision enum is "allow"/"deny"/"ask_user" (bundle/docs/reference/policy-engine.md).
function toGeminiDecision(bucket) {
  return bucket === "ask" ? "ask_user" : bucket;
}

function renderToolRule(names, bucket) {
  return [
    "[[rule]]",
    `toolName = ${tomlToolNameField(names)}`,
    `decision = ${quoteToml(toGeminiDecision(bucket))}`,
    `priority = ${RULE_PRIORITY}`,
  ].join("\n");
}

function renderShellCommandRule(pattern, bucket) {
  const commandPrefix = pattern.map(String).join(" ");
  return [
    "[[rule]]",
    `toolName = ${quoteToml("run_shell_command")}`,
    `commandPrefix = ${quoteToml(commandPrefix)}`,
    `decision = ${quoteToml(toGeminiDecision(bucket))}`,
    `priority = ${RULE_PRIORITY}`,
  ].join("\n");
}

// Flat model shared with Claude/Codex: manifest.behaviors resolves via overrides, then each
// behavior/arbitrary command maps to one rule. "network" kind (go-online) is Codex-only — Gemini
// has no sandbox network gate, same reason Claude's claudePermissions skips it.
export function renderGeminiPolicyRules(manifest, overrides = {}) {
  const behaviors = (manifest.behaviors ?? []).map((b) => ({
    ...b,
    bucket: overrides.behaviors?.[b.id] ?? b.bucket,
  }));

  const commandsByKey = new Map();
  for (const tokens of manifest.commands?.allow ?? []) {
    commandsByKey.set(tokens.map(String).join(" "), { tokens, bucket: "allow" });
  }
  for (const [key, entry] of Object.entries(overrides.commands ?? {})) {
    commandsByKey.set(key, { tokens: entry.tokens, bucket: entry.bucket });
  }

  const rules = [];

  for (const b of behaviors) {
    if (b.kind === "network") continue;
    if (b.kind === "tools") {
      const names = geminiToolNames(b.tools ?? []);
      if (names.length > 0) rules.push(renderToolRule(names, b.bucket));
      continue;
    }
    if (b.kind !== "commands") continue;
    for (const pattern of b.commands ?? []) rules.push(renderShellCommandRule(pattern, b.bucket));
  }

  for (const [, c] of commandsByKey) {
    rules.push(renderShellCommandRule(c.tokens, c.bucket));
  }

  for (const [server, tools] of Object.entries(manifest.mcp ?? {})) {
    if (tools.length === 0) continue;
    rules.push(renderToolRule(tools.map((tool) => `mcp_${server}_${tool}`), "allow"));
  }

  return `${rules.join("\n\n")}\n`;
}

// Gemini's policy directory loads every *.toml file it contains and combines their rules — no
// single generated-block-inside-existing-file merge like Claude/Codex's rootConfig. roborepo owns
// one whole file (roborepo-permissions.toml) inside that directory; anything else present is a
// user's own untouched rule file, never read or merged.
export const GENERATED_POLICY_FILENAME = "roborepo-permissions.toml";

export function renderGeminiPolicyFile(manifest, overrides = {}) {
  const header = "# Generated by roborepo. Source: manifests/inventory/agent-permissions.json\n";
  return `${header}\n${renderGeminiPolicyRules(manifest, overrides)}`;
}
