import fs from "node:fs";
import path from "node:path";
import { repoRoot } from "./paths.mjs";
import { loadPackageCatalog } from "./package-catalog.mjs";

const AUDIT_REL = "docs/internal/skill-invocation-audit.md";
const AUDIT_PATH = path.join(repoRoot, AUDIT_REL);
const GENERATED_MARKER = "<!-- Generated by `roborepo skill audit`; edit package config or skill metadata instead. -->";

function readSkill(entry) {
  const filePath = path.join(entry.sourcePath, "SKILL.md");
  const content = fs.readFileSync(filePath, "utf8").replace(/\r\n/g, "\n");
  const parsed = parseFrontmatter(content);
  return { name: entry.id, filePath, content, policy: entry.policy, ...parsed };
}

function parseFrontmatter(content) {
  const match = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(content);
  if (!match) return { meta: {}, body: content };
  return { meta: parseYamlish(match[1]), body: match[2] };
}

function parseYamlish(frontmatter) {
  const lines = frontmatter.split("\n");
  const meta = {};
  for (let i = 0; i < lines.length; i += 1) {
    const m = /^([A-Za-z0-9_-]+):(?:\s*(.*))?$/.exec(lines[i]);
    if (!m) continue;
    const [, key, raw = ""] = m;
    if (raw === ">" || raw === "|") {
      const block = [];
      while (i + 1 < lines.length && /^(?:\s{2,}|\t)/.test(lines[i + 1])) {
        i += 1;
        block.push(lines[i].replace(/^(?:\s{2}|\t)/, ""));
      }
      meta[key] = block.join(raw === ">" ? " " : "\n").trim();
    } else {
      meta[key] = raw.replace(/^["']|["']$/g, "").trim();
    }
  }
  return meta;
}

function manifestPolicies() {
  return new Map(packageSkillEntries().map((entry) => [entry.id, entry.policy]));
}

function packageSkillEntries() {
  return loadPackageCatalog({ includeUnavailable: true }).flatMap((pkg) =>
    (pkg.resources || [])
      .filter((resource) => resource.type === "skill")
      .map((resource) => ({
        id: resource.id,
        sourcePath: path.join(pkg.sourceRoot, resource.source),
        policy: {
          skill: resource.id,
          risk: resource.risk || "medium",
          invocation: resource.invocation,
          explicit_command: (resource.entrypoints || []).some((entrypoint) => entrypoint.type === "slash-command"),
        },
      }))
  );
}

function findings(skill) {
  const out = [];
  const frontmatter = skill.content.startsWith("---\n")
    ? skill.content.slice(4, skill.content.indexOf("\n---\n", 4))
    : "";
  const unsupported = ["disable-model-invocation", "allowed-tools", "tools", "shell"].filter((key) =>
    Object.prototype.hasOwnProperty.call(skill.meta, key),
  );
  if (unsupported.length) out.push(`frontmatter: ${unsupported.join(", ")}`);
  if (/^!\s*\S/m.test(skill.body)) out.push("dynamic shell line");
  if (/```(?:bash|sh|shell)\s+!/i.test(skill.body)) out.push("dynamic shell code block");
  if (/\b(git push|deploy|release|publish|rm -rf|curl\s|wget\s)\b/i.test(skill.body)) out.push("side-effect keyword");
  if (!String(skill.meta.description || "").trim()) out.push("missing trigger description");
  return out;
}

function recommendation(policy, skillFindings) {
  if (!policy) return "Add manifest policy.";
  if (skillFindings.some((item) => item.includes("dynamic shell") || item.includes("frontmatter"))) {
    return "Review before allowing implicit invocation.";
  }
  if (policy.risk === "high" || policy.invocation === "manual") return "Keep manual-only or command-gated.";
  if (policy.risk === "medium") return "Keep trigger narrow; add near-miss tests.";
  return "Keep auto if trigger remains narrow.";
}

function escapeCell(value) {
  return String(value ?? "").replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}

export function renderSkillAudit() {
  const policies = manifestPolicies();
  const skills = packageSkillEntries().map(readSkill);
  const rows = skills.map((skill) => {
    const policy = policies.get(skill.name);
    const skillFindings = findings(skill);
    return {
      skill: skill.name,
      invocation: policy?.invocation || "missing",
      risk: policy?.risk || "missing",
      explicit: policy ? String(policy.explicit_command) : "missing",
      findings: skillFindings.length ? skillFindings.join("; ") : "none",
      recommendation: recommendation(policy, skillFindings),
    };
  });

  const unknownPolicies = [...policies.keys()].filter((name) => !skills.some((skill) => skill.name === name));
  const dynamicCount = rows.filter((row) => row.findings !== "none").length;

  return `${[
    "# Skill Invocation Audit",
    "",
    GENERATED_MARKER,
    "",
    "## Summary",
    "",
    `- Shared skills: ${skills.length}`,
    `- Package skill resources: ${policies.size}`,
    `- Static findings: ${dynamicCount}`,
    unknownPolicies.length ? `- Unknown manifest entries: ${unknownPolicies.join(", ")}` : "- Unknown manifest entries: none",
    "",
    "## Compatibility Result",
    "",
    "Claude and Codex express manual-only skill behavior in different metadata locations.",
    "Keep shared `SKILL.md` frontmatter portable; use package-backed checks before adding harness-specific manual-only fields.",
    "",
    "| Harness | Manual-only setting | Source |",
    "| --- | --- | --- |",
    "| Claude | `disable-model-invocation: true` | `SKILL.md` frontmatter |",
    "| Codex | `policy.allow_implicit_invocation: false` | `agents/openai.yaml` |",
    "",
    "## Current Shared Skills",
    "",
    "| Skill | Invocation | Risk | Explicit command | Static findings | Recommendation |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows.map((row) =>
      `| \`${escapeCell(row.skill)}\` | ${escapeCell(row.invocation)} | ${escapeCell(row.risk)} | ${escapeCell(row.explicit)} | ${escapeCell(row.findings)} | ${escapeCell(row.recommendation)} |`
    ),
    "",
    "## Static Checks",
    "",
    "The audit flags:",
    "",
    "- harness-specific or broad tool-grant frontmatter",
    "- dynamic shell lines",
    "- dynamic shell code-block hints",
    "- side-effect keywords that deserve manual review",
    "- missing trigger descriptions",
    "",
    "## Next Actions",
    "",
    "1. Add trigger tests for expected matches and near misses, starting with medium-risk skills.",
    "2. Add manual-only rendering/checks only when a skill is intentionally converted away from implicit invocation.",
    "3. Keep high-risk or side-effecting workflows behind explicit commands or hooks.",
    "",
  ].join("\n")}\n`;
}

export function skillAudit(args = []) {
  const checkOnly = args.includes("--check");
  const write = args.includes("--write") || !checkOnly;
  const content = renderSkillAudit();
  const current = fs.existsSync(AUDIT_PATH) ? fs.readFileSync(AUDIT_PATH, "utf8").replace(/\r\n/g, "\n") : "";

  if (checkOnly) {
    if (current === content) {
      console.log(`ok: ${AUDIT_REL}`);
      return;
    }
    console.error(`stale: ${AUDIT_REL} (run roborepo skill audit)`);
    process.exit(1);
  }

  if (write) {
    fs.writeFileSync(AUDIT_PATH, content);
    console.log(`render: ${AUDIT_REL}`);
  }
}
